networks:
  api:
services:
  api:
    command: node index.js
    image: node:17.3.14-alpine
    networks:
      - api
    ports:
      - 3000:3000
    volumes:
      - .:/srv/api
    working_dir: /srv/api
  postgres:
    image: postgres:alpine
    networks:
      - api
  redis:
    image: redis:6.2-alpine
    networks:
      - api
volumes:
  postgres: {}